---
- name: Installing andrewrothstein.curl
  ansible.builtin.include_role:
    name: andrewrothstein.curl
- name: Installing andrewrothstein.wget
  ansible.builtin.include_role:
    name: andrewrothstein.wget
- name: Installing andrewrothstein.iproute
  ansible.builtin.include_role:
    name: andrewrothstein.iproute
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Networking tools os packages...
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ nettools_os_pkgs }}'
    state: present
